<style>
  .fonticon-container>.fonticon-wrap {
    float: left;
    width: 60px;
    height: 60px;
    line-height: 4.8rem;
    text-align: center;
    border-radius: .1875rem;
    margin-right: 1rem;
    margin-bottom: 1.5rem;
  }

  .fonticon-container>.fonticon-wrap>i {
    font-size: 2.28rem;
    transition: all .2s ease-in-out;
  }

  .fonticon-container>.fonticon-classname,
  .fonticon-container>.fonticon-unit {
    display: block;
    font-size: 1.5rem;
    line-height: 1.2;
  }
</style>

@php
  $icons = [
      'icon-activity',
      'icon-airplay',
      'icon-alert-circle',
      'icon-alert-octagon',
      'icon-alert-triangle',
      'icon-align-center',
      'icon-align-justify',
      'icon-align-left',
      'icon-align-right',
      'icon-anchor',
      'icon-aperture',
      'icon-arrow-down-left',
      'icon-arrow-down-right',
      'icon-arrow-down',
      'icon-arrow-left',
      'icon-arrow-right',
      'icon-arrow-up-left',
      'icon-arrow-up-right',
      'icon-arrow-up',
      'icon-at-sign',
      'icon-award',
      'icon-bar-chart-2',
      'icon-bar-chart',
      'icon-battery-charging',
      'icon-battery',
      'icon-bell-off',
      'icon-bell',
      'icon-bluetooth',
      'icon-bold',
      'icon-book',
      'icon-bookmark',
      'icon-box',
      'icon-briefcase',
      'icon-calendar',
      'icon-camera-off',
      'icon-camera',
      'icon-cast',
      'icon-check-circle',
      'icon-check-square',
      'icon-check',
      'icon-chevron-down',
      'icon-chevron-left',
      'icon-chevron-right',
      'icon-chevron-up',
      'icon-chevrons-down',
      'icon-chevrons-left',
      'icon-chevrons-right',
      'icon-chevrons-up',
      'icon-chrome',
      'icon-circle',
      'icon-clipboard',
      'icon-clock',
      'icon-cloud-drizzle',
      'icon-cloud-lightning',
      'icon-cloud-off',
      'icon-cloud-rain',
      'icon-cloud-snow',
      'icon-cloud',
      'icon-codepen',
      'icon-command',
      'icon-compass',
      'icon-copy',
      'icon-corner-down-left',
      'icon-corner-down-right',
      'icon-corner-left-down',
      'icon-corner-left-up',
      'icon-corner-right-down',
      'icon-corner-right-up',
      'icon-corner-up-left',
      'icon-corner-up-right',
      'icon-cpu',
      'icon-credit-card',
      'icon-crop',
      'icon-crosshair',
      'icon-delete',
      'icon-disc',
      'icon-download-cloud',
      'icon-download',
      'icon-droplet',
      'icon-edit-2',
      'icon-edit-1',
      'icon-edit',
      'icon-external-link',
      'icon-eye-off',
      'icon-eye',
      'icon-facebook',
      'icon-fast-forward',
      'icon-feather',
      'icon-file-minus',
      'icon-file-plus',
      'icon-file-text',
      'icon-file',
      'icon-film',
      'icon-filter',
      'icon-flag',
      'icon-folder',
      'icon-github',
      'icon-gitlab',
      'icon-globe',
      'icon-grid',
      'icon-hash',
      'icon-headphones',
      'icon-heart',
      'icon-help-circle',
      'icon-image',
      'icon-inbox',
      'icon-info',
      'icon-instagram',
      'icon-italic',
      'icon-layers',
      'icon-layout',
      'icon-life-buoy',
      'icon-link-2',
      'icon-link',
      'icon-list',
      'icon-loader',
      'icon-lock',
      'icon-log-in',
      'icon-log-out',
      'icon-mail',
      'icon-map-pin',
      'icon-map',
      'icon-maximize-2',
      'icon-maximize',
      'icon-menu',
      'icon-message-circle',
      'icon-message-square',
      'icon-mic-off',
      'icon-mic',
      'icon-minimize-2',
      'icon-minimize',
      'icon-minus-circle',
      'icon-minus-square',
      'icon-minus',
      'icon-monitor',
      'icon-moon',
      'icon-more-horizontal',
      'icon-more-vertical',
      'icon-move',
      'icon-music',
      'icon-navigation-2',
      'icon-navigation',
      'icon-octagon',
      'icon-package',
      'icon-paperclip',
      'icon-pause-circle',
      'icon-pause',
      'icon-percent',
      'icon-phone-call',
      'icon-phone-forwarded',
      'icon-phone-incoming',
      'icon-phone-missed',
      'icon-phone-off',
      'icon-phone-outgoing',
      'icon-phone',
      'icon-pie-chart',
      'icon-play-circle',
      'icon-play',
      'icon-plus-circle',
      'icon-plus-square',
      'icon-plus',
      'icon-pocket',
      'icon-power',
      'icon-printer',
      'icon-radio',
      'icon-refresh-ccw',
      'icon-refresh-cw',
      'icon-repeat',
      'icon-rewind',
      'icon-rotate-ccw',
      'icon-rotate-cw',
      'icon-save',
      'icon-scissors',
      'icon-search',
      'icon-server',
      'icon-settings',
      'icon-share-2',
      'icon-share',
      'icon-shield',
      'icon-shopping-cart',
      'icon-shuffle',
      'icon-sidebar',
      'icon-skip-back',
      'icon-skip-forward',
      'icon-slack',
      'icon-slash',
      'icon-sliders',
      'icon-smartphone',
      'icon-speaker',
      'icon-square',
      'icon-star',
      'icon-stop-circle',
      'icon-sun',
      'icon-sunrise',
      'icon-sunset',
      'icon-tablet',
      'icon-tag',
      'icon-target',
      'icon-thermometer',
      'icon-thumbs-down',
      'icon-thumbs-up',
      'icon-toggle-left',
      'icon-toggle-right',
      'icon-trash-2',
      'icon-trash',
      'icon-trending-down',
      'icon-trending-up',
      'icon-triangle',
      'icon-tv',
      'icon-twitter',
      'icon-type',
      'icon-umbrella',
      'icon-underline',
      'icon-unlock',
      'icon-upload-cloud',
      'icon-upload',
      'icon-user-check',
      'icon-user-minus',
      'icon-user-plus',
      'icon-user-x',
      'icon-user',
      'icon-users',
      'icon-video-off',
      'icon-video',
      'icon-voicemail',
      'icon-volume-1',
      'icon-volume-2',
      'icon-volume-x',
      'icon-volume',
      'icon-watch',
      'icon-wifi-off',
      'icon-wifi',
      'icon-wind',
      'icon-x-circle',
      'icon-x-square',
      'icon-x',
      'icon-zap',
      'icon-zoom-in',
      'icon-zoom-out',
  ];

@endphp
<div>
  <div class="feather-icons overflow-hidden row">

    @foreach ($icons as $row)
      <div class="col-md-4 fonticon-container">
        <div class="fonticon-wrap">
          <i class="feather {{ $row }}"></i>
        </div>
        <label class="fonticon-classname mt-1">{{ $row }}</label>
        <input class="form-control" value="feather {{ $row }}" readonly style="width:65%">
      </div>
    @endforeach

  </div>
</div>
